# Generated by Django 4.0.6 on 2023-05-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='项目名称')),
                ('creater', models.CharField(blank=True, max_length=30, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建的时间')),
                ('mock_dec', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目描述')),
            ],
        ),
    ]
