# Generated by Django 4.0.6 on 2023-05-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PressurePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='计划名称')),
                ('script', models.CharField(blank=True, max_length=30, null=True, verbose_name='压测脚本')),
                ('project_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目描述')),
                ('pressure_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目描述')),
            ],
        ),
    ]
