# Generated by Django 4.0.6 on 2023-05-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressureplan',
            name='project_id',
            field=models.IntegerField(blank=True, max_length=32, null=True, verbose_name='项目ID'),
        ),
    ]
