# Generated by Django 4.0.6 on 2023-05-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressure', '0003_pressureplan_plan_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True, verbose_name='创建的时间')),
                ('status', models.CharField(blank=True, default='队列中', max_length=10, null=True)),
                ('desc', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('project_id', models.IntegerField(default=0)),
                ('project_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目名称')),
            ],
        ),
        migrations.AlterField(
            model_name='pressureplan',
            name='plan_desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='计划描述'),
        ),
    ]
