# Generated by Django 4.0.6 on 2023-05-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressure', '0004_tasks_alter_pressureplan_plan_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='mq_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='任务的ID'),
        ),
        migrations.AlterField(
            model_name='pressureplan',
            name='project_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='项目ID'),
        ),
    ]
