# Generated by Django 4.0.6 on 2023-05-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressure', '0006_alter_tasks_mq_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressureplan',
            name='script',
        ),
        migrations.AlterField(
            model_name='pressureplan',
            name='pressure_type',
            field=models.CharField(blank=True, default='[]', max_length=1000, null=True, verbose_name='压测类型'),
        ),
    ]
