# Generated by Django 4.0.6 on 2023-05-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressure', '0007_remove_pressureplan_script_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBScripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='计划名称')),
                ('start_time', models.DateTimeField(null=True, verbose_name='创建的时间')),
                ('desc', models.CharField(blank=True, default='', max_length=300, null=True)),
            ],
        ),
    ]
