# Generated by Django 4.0.6 on 2023-05-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressure', '0008_dbscripts'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbscripts',
            name='auther',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='开发者'),
        ),
        migrations.AddField(
            model_name='dbscripts',
            name='model',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='脚本类型'),
        ),
        migrations.AlterField(
            model_name='dbscripts',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='脚本名称'),
        ),
    ]
