# Generated by Django 4.0.6 on 2023-05-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressure', '0009_dbscripts_auther_dbscripts_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbscripts',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='脚本名称'),
        ),
    ]
