# Generated by Django 4.0.6 on 2023-04-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mock_name', models.CharField(blank=True, max_length=30, null=True)),
                ('mock_creater', models.CharField(blank=True, max_length=30, null=True)),
                ('mock_crate_time', models.DateTimeField(null=True, verbose_name='创建的时间')),
            ],
        ),
    ]
