# Generated by Django 4.0.6 on 2023-04-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockproject',
            name='mock_dec',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='mock专项描述'),
        ),
        migrations.AlterField(
            model_name='mockproject',
            name='mock_creater',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='专项创建者'),
        ),
        migrations.AlterField(
            model_name='mockproject',
            name='mock_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='专项名称'),
        ),
    ]
