# Generated by Django 4.0.6 on 2023-04-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_service', '0002_mockproject_mock_dec_alter_mockproject_mock_creater_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='mock单元名称')),
                ('state', models.BooleanField(default=False, verbose_name='状态')),
                ('project_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='项目ID')),
            ],
        ),
    ]
