# Generated by Django 4.0.6 on 2023-04-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_service', '0004_mockunit_catch_url_mockunit_mock_response_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockproject',
            name='mock_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mockproject',
            name='run_counts',
            field=models.IntegerField(default=0),
        ),
    ]
