# Generated by Django 4.0.6 on 2023-04-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_service', '0005_mockproject_mock_counts_mockproject_run_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockunit',
            name='catch_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='请求的URL'),
        ),
        migrations.AlterField(
            model_name='mockunit',
            name='mock_response_body',
            field=models.TextField(blank=True, default='', null=True, verbose_name='mock响应体'),
        ),
    ]
