# Generated by Django 4.0.6 on 2023-04-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_service', '0006_alter_mockunit_catch_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockproject',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
