# Generated by Django 4.0.6 on 2023-04-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_service', '0009_mockunit_mock_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockunit',
            name='mock_time',
            field=models.FloatField(default=''),
        ),
    ]
