# Generated by Django 4.0.6 on 2023-04-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_service', '0011_alter_mockunit_mock_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockproject',
            name='black_hosts',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mockproject',
            name='catch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mockproject',
            name='catch_log',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='mockproject',
            name='catch_time',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mockproject',
            name='white_hosts',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
